//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllocationAudit
    {
        public string Id { get; set; }
        public int AllocationId { get; set; }
        public Nullable<int> TestCaseId { get; set; }
        public int CycleId { get; set; }
        public int UserId { get; set; }
        public System.DateTime PlannedDate { get; set; }
        public Nullable<System.DateTime> ExecutedDate { get; set; }
        public string Comments { get; set; }
        public int ReadyForReleaseId { get; set; }
        public Nullable<int> ReleasedByUserId { get; set; }
        public string ReferenceNumber { get; set; }
        public string DebitOrPurchaseAccNo { get; set; }
        public string DebitOrPurchaseCurrency { get; set; }
        public string DebitOrPurchaseAmt { get; set; }
        public string CreditOrSellAccNo { get; set; }
        public string CreditOrSellCurrency { get; set; }
        public string CreditOrSellAmount { get; set; }
        public string WSSDealRefNumber { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public string Rates { get; set; }
        public string ChargeAccNumber { get; set; }
        public string ChargeAmount { get; set; }
        public string ChargeAccNumber1 { get; set; }
        public string ChargeAmount1 { get; set; }
        public string ChargeAccNumber2 { get; set; }
        public string ChargeAmount2 { get; set; }
        public string ChargeAccNumber3 { get; set; }
        public string ChargeAmount3 { get; set; }
        public string BOPCAT { get; set; }
        public string DecisionMatrix { get; set; }
        public string SwiftAddress { get; set; }
        public string BOPSplits { get; set; }
        public string SettlementSplits { get; set; }
        public string CCNumber { get; set; }
        public string Tax { get; set; }
        public Nullable<int> BlockedReasonId { get; set; }
        public string BlockedReasonComments { get; set; }
        public Nullable<int> RequestToReleaseUserId { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Col1 { get; set; }
        public Nullable<int> Col2 { get; set; }
        public Nullable<int> Col3 { get; set; }
        public string Col4 { get; set; }
        public string Col5 { get; set; }
        public string Col6 { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> MCPEResultId { get; set; }
        public string MCPEComments { get; set; }
        public Nullable<System.DateTime> MCPEPlannedDate { get; set; }
        public Nullable<System.DateTime> MCPEVerifiedDate { get; set; }
        public Nullable<int> MCPEVerifiedBy { get; set; }
        public Nullable<int> ExceptionResultId { get; set; }
        public string ExceptionComments { get; set; }
        public Nullable<System.DateTime> ExceptionPlannedDate { get; set; }
        public Nullable<System.DateTime> ExceptionVerifiedDate { get; set; }
        public Nullable<int> ExceptionVerifiedBy { get; set; }
        public Nullable<int> GLResultId { get; set; }
        public string GLComments { get; set; }
        public Nullable<System.DateTime> GLPlannedDate { get; set; }
        public Nullable<System.DateTime> GLVerifiedDate { get; set; }
        public Nullable<int> GLVerifiedBy { get; set; }
        public Nullable<int> SwiftResultId { get; set; }
        public string SwiftComments { get; set; }
        public Nullable<System.DateTime> SwiftPlannedDate { get; set; }
        public Nullable<System.DateTime> SwiftVerifiedDate { get; set; }
        public Nullable<int> SwiftVerifiedBy { get; set; }
        public Nullable<int> Rec7ResultId { get; set; }
        public string Rec7Comments { get; set; }
        public Nullable<System.DateTime> Rec7PlannedDate { get; set; }
        public Nullable<System.DateTime> Rec7VerifiedDate { get; set; }
        public Nullable<int> Rec7VerifiedBy { get; set; }
        public Nullable<int> WSSResultId { get; set; }
        public string WSSComments { get; set; }
        public Nullable<System.DateTime> WSSPlannedDate { get; set; }
        public Nullable<System.DateTime> WSSVerifiedDate { get; set; }
        public Nullable<int> WSSVerifiedBy { get; set; }
        public Nullable<int> FinSurvResultId { get; set; }
        public string FinSurvComments { get; set; }
        public Nullable<System.DateTime> FinSurvPlannedDate { get; set; }
        public Nullable<System.DateTime> FinSurvVerifiedDate { get; set; }
        public Nullable<int> FinSurvVerifiedBy { get; set; }
        public string FinSurvAddlComments { get; set; }
        public Nullable<int> SanctionsResultId { get; set; }
        public string SanctionsComments { get; set; }
        public Nullable<System.DateTime> SanctionsPlannedDate { get; set; }
        public Nullable<System.DateTime> SanctionsVerifiedDate { get; set; }
        public Nullable<int> SanctionsVerifiedBy { get; set; }
        public Nullable<int> CASA_ACC_CR { get; set; }
        public Nullable<int> CASA_ACC_DR { get; set; }
        public Nullable<int> MCA_ACC_DR { get; set; }
        public Nullable<int> MCA_ACC_CR { get; set; }
        public Nullable<int> FTS_AC_DR_GLPC07C { get; set; }
        public Nullable<int> FTS_AC_CR_GLPC07C_REP { get; set; }
        public Nullable<int> CASA_CNTR_ACS_DR_WSP220_REP { get; set; }
        public Nullable<int> CASA_CNTR_ACS_CR_WSP220_REP { get; set; }
    }
}
