//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cycle
    {
        public Cycle()
        {
            this.Allocations = new HashSet<Allocation>();
            this.CycleDates = new HashSet<CycleDate>();
            this.CycleTesters = new HashSet<CycleTester>();
            this.DownTimes = new HashSet<DownTime>();
        }
    
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public string CycleName { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Allocation> Allocations { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<CycleDate> CycleDates { get; set; }
        public virtual ICollection<CycleTester> CycleTesters { get; set; }
        public virtual ICollection<DownTime> DownTimes { get; set; }
    }
}
