//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownStream
    {
        public DownStream()
        {
            this.DownStreamUsers = new HashSet<DownStreamUser>();
        }
    
        public int Id { get; set; }
        public string DownStreamName { get; set; }
    
        public virtual ICollection<DownStreamUser> DownStreamUsers { get; set; }
    }
}
