//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Cycles = new HashSet<Cycle>();
            this.TestCases = new HashSet<TestCas>();
        }
    
        public int Id { get; set; }
        public int ProjectUId { get; set; }
        public string ProjectName { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ICollection<Cycle> Cycles { get; set; }
        public virtual ICollection<TestCas> TestCases { get; set; }
    }
}
