//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultList
    {
        public ResultList()
        {
            this.Allocations = new HashSet<Allocation>();
            this.Allocations1 = new HashSet<Allocation>();
            this.Allocations2 = new HashSet<Allocation>();
            this.Allocations3 = new HashSet<Allocation>();
            this.Allocations4 = new HashSet<Allocation>();
            this.Allocations5 = new HashSet<Allocation>();
            this.Allocations6 = new HashSet<Allocation>();
            this.Allocations7 = new HashSet<Allocation>();
            this.Allocations8 = new HashSet<Allocation>();
            this.Allocations9 = new HashSet<Allocation>();
            this.Allocations10 = new HashSet<Allocation>();
            this.Allocations11 = new HashSet<Allocation>();
            this.Allocations12 = new HashSet<Allocation>();
            this.Allocations13 = new HashSet<Allocation>();
            this.Allocations14 = new HashSet<Allocation>();
            this.Allocations15 = new HashSet<Allocation>();
        }
    
        public int Id { get; set; }
        public string ResultName { get; set; }
        public string ResultDescription { get; set; }
    
        public virtual ICollection<Allocation> Allocations { get; set; }
        public virtual ICollection<Allocation> Allocations1 { get; set; }
        public virtual ICollection<Allocation> Allocations2 { get; set; }
        public virtual ICollection<Allocation> Allocations3 { get; set; }
        public virtual ICollection<Allocation> Allocations4 { get; set; }
        public virtual ICollection<Allocation> Allocations5 { get; set; }
        public virtual ICollection<Allocation> Allocations6 { get; set; }
        public virtual ICollection<Allocation> Allocations7 { get; set; }
        public virtual ICollection<Allocation> Allocations8 { get; set; }
        public virtual ICollection<Allocation> Allocations9 { get; set; }
        public virtual ICollection<Allocation> Allocations10 { get; set; }
        public virtual ICollection<Allocation> Allocations11 { get; set; }
        public virtual ICollection<Allocation> Allocations12 { get; set; }
        public virtual ICollection<Allocation> Allocations13 { get; set; }
        public virtual ICollection<Allocation> Allocations14 { get; set; }
        public virtual ICollection<Allocation> Allocations15 { get; set; }
    }
}
