//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCas
    {
        public TestCas()
        {
            this.Allocations = new HashSet<Allocation>();
        }
    
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> SystemId { get; set; }
        public Nullable<int> SubSystem1Id { get; set; }
        public Nullable<int> SubSystem2Id { get; set; }
        public long ScenarioNumber { get; set; }
        public string ScenarioName { get; set; }
        public string ScenarioDescription { get; set; }
        public string Comments { get; set; }
    
        public virtual ICollection<Allocation> Allocations { get; set; }
        public virtual Project Project { get; set; }
        public virtual TestSystem Module { get; set; }
        public virtual TestSystem SubSystem1 { get; set; }
        public virtual TestSystem SubSystem2 { get; set; }
        public virtual TestSystem System { get; set; }
    }
}
