//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Allocations = new HashSet<Allocation>();
            this.Allocations1 = new HashSet<Allocation>();
            this.Allocations2 = new HashSet<Allocation>();
            this.CycleTesters = new HashSet<CycleTester>();
            this.DownStreamUsers = new HashSet<DownStreamUser>();
            this.Teams = new HashSet<Team>();
            this.UserRoles = new HashSet<UserRole>();
            this.Allocations3 = new HashSet<Allocation>();
            this.Allocations11 = new HashSet<Allocation>();
            this.Allocations21 = new HashSet<Allocation>();
            this.Allocations31 = new HashSet<Allocation>();
            this.Allocations5 = new HashSet<Allocation>();
            this.Allocations7 = new HashSet<Allocation>();
            this.Allocations8 = new HashSet<Allocation>();
            this.Allocations10 = new HashSet<Allocation>();
        }
    
        public int Id { get; set; }
        public string EmpId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> TeamId { get; set; }
    
        public virtual ICollection<Allocation> Allocations { get; set; }
        public virtual ICollection<Allocation> Allocations1 { get; set; }
        public virtual ICollection<Allocation> Allocations2 { get; set; }
        public virtual ICollection<CycleTester> CycleTesters { get; set; }
        public virtual ICollection<DownStreamUser> DownStreamUsers { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
        public virtual Team Team { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
        public virtual ICollection<Allocation> Allocations3 { get; set; }
        public virtual ICollection<Allocation> Allocations11 { get; set; }
        public virtual ICollection<Allocation> Allocations21 { get; set; }
        public virtual ICollection<Allocation> Allocations31 { get; set; }
        public virtual ICollection<Allocation> Allocations5 { get; set; }
        public virtual ICollection<Allocation> Allocations7 { get; set; }
        public virtual ICollection<Allocation> Allocations8 { get; set; }
        public virtual ICollection<Allocation> Allocations10 { get; set; }
    }
}
